name: Implantação Lovable

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Gatilho manual para execução do workflow

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist/
          
      - name: Ensure .htaccess is in dist directory
        run: |
          echo "# Configurações otimizadas para Hostinger (Apache)
          
          # Habilitar reescrita de URL para SPA (crucial para React Router)
          <IfModule mod_rewrite.c>
              RewriteEngine On
              RewriteBase /quiz-de-estilo/
          
              # Se o arquivo solicitado não existir fisicamente, redirecionar para index.html
              RewriteCond %{REQUEST_FILENAME} !-f
              RewriteCond %{REQUEST_FILENAME} !-d
              RewriteRule ^(.*)$ index.html [L,QSA]
          </IfModule>" > dist/.htaccess
          
      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.giselegalvao.com.br
          username: u116045488.giselegalvao
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /u116045488/domains/giselegalvao.com.br/public_html/quiz-de-estilo/
          dangerous-clean-slate: true
